require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec 
  
AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
    
Style/GuardClause:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 1000

Style/FrozenStringLiteralComment:
  Enabled: false


Rails/HasManyOrHasOneDependent:
   Enabled: false 

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/LetSetup:
  Exclude:
    - 'spec/requests/*'

RSpec/MessageChain: 
  Exclude:
    - 'spec/models/*'   
