# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coaching_app_development_1
  host: localhost
  username: root
  password: root

test:
  <<: *default
  database: coaching_app_test_1
  host: localhost
  username: root
  password: root

production:
  <<: *default
  database: coaching_app_production
  username: coaching_app
  password: <%= ENV['COACHING_APP_DATABASE_PASSWORD'] %>
